### ISSUE TITLE
psutil.get_process_list() is deprecated

### ISSUE THREAD

**Issue by emdio** [EvilKhaosKat/ram_overusage_notifier#1]
Simply making this change seems to fix the issue

#processes = psutil.get_process_list()
processes = list(psutil.process_iter())

**Comment by romanthekat** [comment]
Sounds nice, thanks @emdio! ^_^

I hope I'll update it in foreseeable future

**Comment by romanthekat** [comment]
updated to `psutil>=5.6.7` =^__^=
